<?php
/**
 * Query object for the redirects table.
 *
 * @package DuckDev\FourNotFour
 */

declare( strict_types = 1 );

namespace DuckDev\FourNotFour\Database\Queries;

// If this file is called directly, abort.
defined( 'ABSPATH' ) || exit;

use BerlinDB\Database\Query;

/**
 * Class Redirect
 *
 * @since   4.0.0
 * @package DuckDev\FourNotFour\Database\Queries
 */
class Redirect extends Query {

	/**
	 * Table name (without WP prefix).
	 *
	 * @since 4.0.0
	 * @var string
	 */
	protected $table_name = '404_to_301_redirects';

	/**
	 * Short alias used inside SQL generated by BerlinDB.
	 *
	 * @since 4.0.0
	 * @var string
	 */
	protected $table_alias = 'r';

	/**
	 * Schema class used to validate the query columns.
	 *
	 * @since 4.0.0
	 * @var string
	 */
	protected $table_schema = \DuckDev\FourNotFour\Database\Schemas\Redirects::class;

	/**
	 * Item name in singular form.
	 *
	 * @since 4.0.0
	 * @var string
	 */
	protected $item_name = 'redirect';

	/**
	 * Item name in plural form.
	 *
	 * @since 4.0.0
	 * @var string
	 */
	protected $item_name_plural = 'redirects';

	/**
	 * Row class used to hydrate rows.
	 *
	 * @since 4.0.0
	 * @var string
	 */
	protected $item_shape = \DuckDev\FourNotFour\Database\Rows\Redirect::class;

	/**
	 * Object cache group.
	 *
	 * @since 4.0.0
	 * @var string
	 */
	protected $cache_group = '404_to_301_redirects';
}
