<?php
/**
 * Query object for the 404 logs table.
 *
 * BerlinDB's `Query` base class gives us a full WP_Query-style API
 * (where clauses, ordering, pagination, caching, meta-style queries).
 * We just point it at the table + row shape and let it work.
 *
 * @package DuckDev\FourNotFour
 */

declare( strict_types = 1 );

namespace DuckDev\FourNotFour\Database\Queries;

// If this file is called directly, abort.
defined( 'ABSPATH' ) || exit;

use BerlinDB\Database\Query;

/**
 * Class Log
 *
 * @since   4.0.0
 * @package DuckDev\FourNotFour\Database\Queries
 */
class Log extends Query {

	/**
	 * Table name (without WP prefix). Matches `Database\Tables\Logs::$name`.
	 *
	 * @since 4.0.0
	 * @var string
	 */
	protected $table_name = '404_to_301_logs';

	/**
	 * Short alias used inside SQL generated by BerlinDB.
	 *
	 * @since 4.0.0
	 * @var string
	 */
	protected $table_alias = 'l';

	/**
	 * Schema class used to validate the query columns.
	 *
	 * @since 4.0.0
	 * @var string
	 */
	protected $table_schema = \DuckDev\FourNotFour\Database\Schemas\Logs::class;

	/**
	 * Item name in singular form.
	 *
	 * @since 4.0.0
	 * @var string
	 */
	protected $item_name = 'log';

	/**
	 * Item name in plural form.
	 *
	 * @since 4.0.0
	 * @var string
	 */
	protected $item_name_plural = 'logs';

	/**
	 * Row class used to hydrate rows.
	 *
	 * @since 4.0.0
	 * @var string
	 */
	protected $item_shape = \DuckDev\FourNotFour\Database\Rows\Log::class;

	/**
	 * Object cache group. BerlinDB invalidates by writing to this key.
	 *
	 * @since 4.0.0
	 * @var string
	 */
	protected $cache_group = '404_to_301_logs';
}
