# Travis CI configuration file.

language: php

# Configure caches
cache:
  apt: true

# 5.6 is required for Codeception.
php:
    - 5.6
    - 7.0

# Run against regular and multisite.
env:
    - WP_MULTISITE=0
    - WP_MULTISITE=1

# Use the new container-based infrastructure (it's faster).
sudo: false

matrix:
    include:
        - php: hhvm
          env: WP_MULTISITE=0
          sudo: required
          dist: trusty
          group: edge
          addons:
            apt:
              packages:
              - mysql-server-5.6
              - mysql-client-core-5.6
              - mysql-client-5.6
        - php: nightly
          env: WP_MULTISITE=0
    allow_failures:
        - php: hhvm
        - php: nightly
    fast_finish: true

before_script:
    # Define vars.
    - export WP_VERSION=master
    - export WP_DEVELOP_DIR=/tmp/wordpress
    - export WP_CORE_DIR=/tmp/wordpress/src
    - export WP_CEPT_SERVER='127.0.0.1:8888'
    # Install WordPress
    - source misc/deploy-wordpress.sh
    - install-wordpress
    # Start up a web server.
    - php -S "$WP_CEPT_SERVER" -t "$WP_CORE_DIR" >/dev/null 2>&1 &
    # Start up the webdriver.
    - phantomjs --webdriver=4444 >/dev/null 2>&1 &
    # Install Codeception and WP Browser.
    # Doing this last gives the webdriver and server time to start up.
    - composer install --prefer-source

script:
    - vendor/bin/wpcept run

# EOF